name: Eslint
on:
  push:

jobs:
  check_eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        sudo npm install -g eslint
        npm install
    - run: eslint lib --ext .js,.jsx,.ts,.tsx
    - run: npm test